import requests
import argparse
import os

from src.api_parameters import ApiParameters
from src.secret import Secret
from src.utils import get_output_name, image_to_base64
from src.options import *


def main():
    PROMPT = ''
    IMAGE_URI = ''
    DURATION = Duration(8)

    # ---- START of ARGUMENT PARSING ----
    parser = argparse.ArgumentParser(description='A sample program for LTX Video.')
    parser.add_argument(
        '-p',
        '--prompt',
        metavar='PROMPT_FILE',
        required=True,
        type=str,
        help='A plain text file or markdown file for prompt.'
    )
    parser.add_argument(
        '-i',
        '--image_uri',
        metavar='IMAGE_URI',
        type=str,
        help='The image URI for the first frame of the video. If not provided, the video will be generated by prompt only.'
    )
    parser.add_argument(
        '-d',
        '--duration',
        metavar='DURATION',
        type=int,
        default=8,
        help='The duration of the video in seconds. Default is 8 seconds. Options: {}'.format(', '.join([str(d.value) for d in Duration]))
    )
    args = parser.parse_args()
    
    # Check prompt file
    if not os.path.isfile(args.prompt):
        print('[Error] File {} does not exist.'.format(args.prompt))
        return

    with open(args.prompt, 'r') as file:
        PROMPT = file.read()
        if PROMPT == '':
            print('[Error] File {} is empty.'.format(args.prompt))
            return

    # Check image uri
    if args.image_uri and not os.path.isfile(args.image_uri):
        print('[Error] Image URI {} is invalid.'.format(args.image_uri))
        return

    if args.image_uri:
        IMAGE_URI = image_to_base64(args.image_uri)
        if IMAGE_URI == '':
            print('[Error] Image URI {} is invalid.'.format(args.image_uri))
            return

    # Check duration
    if args.duration not in [d.value for d in Duration]:
        print('[Error] Duration {} is invalid.'.format(args.duration))
        return
    DURATION = Duration(args.duration)
    # ---- END of ARGUMENT PARSING ----

    # Prepare Api Parameters
    secret = Secret()
    output_name = get_output_name()

    api_params = ApiParameters(
        prompt=PROMPT,
        duration=DURATION,
        image_uri=IMAGE_URI,
    )

    # Api Calls
    print('[Info] Prompt file: {}'.format(args.prompt))
    if len(api_params.image_uri) > 0:
        print('[Info] Image URI: {}'.format(args.image_uri))
    print('[Info] Video Duration: {}s'.format(api_params.get_payload().get('duration')))
    print('[Info] Sending request to {}'.format(api_params.get_url()))
    response = requests.post(
        api_params.get_url(),
        json=api_params.get_payload(),
        headers=secret.get_headers(),
    )

    # Error Handling
    if response.status_code != 200:
        resp_json = response.json()
        error = None
        if type(resp_json) is dict:
            error = resp_json['error']
        if type(error) is dict and 'message' in error.keys():
            print('[Error] {}'.format(error.get('type')))
            print('[Error] {}'.format(error.get('message')))
        else:
            print(response.json())
        return

    # Success
    with open(output_name, 'wb') as f:
        f.write(response.content)
        print('[Info] Video saved as {}'.format(output_name))

if __name__ == '__main__':
    main()